name: Gerar Executável Windows

on:
  push:
    branches: [ "main" ] # O processo inicia sempre que você der 'push' na branch main

jobs:
  build:
    runs-on: windows-latest # Usa um servidor Windows real da GitHub

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar Dependências
      run: |
        python -m pip install --upgrade pip
        pip install pdfplumber pypdf pyinstaller rich

    - name: Gerar Executável com PyInstaller
      # Aqui adicionamos o ícone e o nome do programa!
      run: |
        python -m PyInstaller --onefile --console --icon="favicon.ico" --name "Sistema LRO" --collect-all rich main.py

    - name: Upload do Executável
      uses: actions/upload-artifact@v4
      with:
        name: Sistema-LRO-Windows
        # O caminho de saída atualiza para refletir o novo nome do executável
        path: dist/Sistema LRO.exe